"""
Constants for Netflix-Style Media Player
Colors, sizes, and style definitions
"""

# Netflix Color Scheme
NETFLIX_RED = "#e50914"
NETFLIX_BLACK = "#141414"
NETFLIX_DARK_GRAY = "#2f2f2f"
NETFLIX_LIGHT_GRAY = "#808080"

# Control Bar Dimensions (Minimal VLC-style)
CONTROL_BAR_HEIGHT = 88
CONTROL_PADDING = 10
CONTROL_PADDING_BOTTOM = 12
TIMELINE_HEIGHT = 3
TIMELINE_HEIGHT_HOVER = 5
TIMELINE_BOTTOM_MARGIN = 10

# Button Sizes
BUTTON_SIZE_SMALL = 32
BUTTON_SIZE_LARGE = 45
BUTTON_SPACING = 6

# Font Sizes
FONT_SIZE_SMALL = 11
FONT_SIZE_MEDIUM = 13
FONT_SIZE_LARGE = 16

# Animation Durations
FADE_DURATION = 200
CONTROL_HIDE_DELAY = 3000

# Popover Dimensions
POPOVER_MIN_WIDTH = 320
POPOVER_MAX_HEIGHT = 380
